include "local.conf"

ktor {
  deployment {
    port = 8000
  }

  application {
    modules = [
      plugins.DIKt.configureDependencyInjection,
      plugins.ExposedKt.configureExposed,
      plugins.MonitoringKt.configureMonitoring,
      plugins.SecurityKt.configureSecurity,
      plugins.SerializationKt.configureSerialization,
      plugins.SwaggerKt.configureSwagger,
      plugins.CallLoggingKt.configureCallLogging,
      plugins.ResourcesKt.configureResources,
      plugins.StatusPagesKt.configureStatusPages,
      plugins.SSEKt.configureSSE,
      plugins.CORSKt.configureCORS,
      controller.ControllersKt.configureControllers,
      MainKt.main,
    ]
  }
}