ktor:
  deployment:
    port: 8080
  application:
    modules:
      - at.ilja_busch.HttpKt.configureHttp
      - at.ilja_busch.MonitoringKt.configureMonitoring
      - at.ilja_busch.SerializationKt.configureSerialization
      - at.ilja_busch.SecurityKt.configureSecurity
      - at.ilja_busch.RequestValidationKt.configureRequestValidation
      - at.ilja_busch.DIKt.configureDependencyInjection
      - at.ilja_busch.ExposedKt.configureExposed
      - at.ilja_busch.PostgresKt.configurePostgres
      - at.ilja_busch.RoutingKt.configureRouting
