include "local.conf"

ktor {
  deployment {
    port = 8000
    port = ${?PORT}
  }

  application {
    modules = [
      plugins.DIKt.configureDependencyInjection,
      plugins.ExposedKt.configureExposed,
      plugins.MonitoringKt.configureMonitoring,
      plugins.SecurityKt.configureSecurity,
      plugins.SerializationKt.configureSerialization,
      plugins.SwaggerKt.configureSwagger,
      plugins.CallLoggingKt.configureCallLogging,
      plugins.ResourcesKt.configureResources,
      plugins.StatusPagesKt.configureStatusPages,
      plugins.SSEKt.configureSSE,
      plugins.CORSKt.configureCORS,
      controller.ControllersKt.configureControllers,
      MainKt.main,
    ]
  }
}

postgres {
  active = ${?POSTGRES_ACTIVE}
  url = ${?POSTGRES_URL}
  user = ${?POSTGRES_USER}
  password = ${?POSTGRES_PASSWORD}
}

auth {
  base = ${?AUTH_BASE_URI}
  realm = ${?AUTH_REALM}
  clientId = ${?AUTH_CLIENTID}
}