include "local.conf"

ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [
      plugins.ExposedKt.configureExposed,
      plugins.MonitoringKt.configureMonitoring,
      plugins.SecurityKt.configureSecurity,
      plugins.SerializationKt.configureSerialization,
      plugins.SwaggerKt.configureSwagger,
      controller.ControllersKt.configureControllers,
      plugins.DIKt.configureDependencyInjection,
      MainKt.main,
    ]
  }
}